# Dependencies
highlighter:      rouge
layout: default
comments: true
# other options
gems:
  - jekyll-paginate
  - jekyll-feed

# Permalinks
permalink:              /blog/:categories/:title/
# permalink:            blog/:categories/:year/:month/:day/:title/

# Setup
title:            'Mesfin Diro Chaka'
name:             'Mesfin Diro Chaka'
#tagline:          ''
description:      'Computational Data Scientist'
url:              http://mesfind.github.io
baseurl:
# blogurl:          /blog/

# Assets
images:         '/img'
pdfs:           '/pdf'

author:
  name:           'Mesfin Diro Chaka'
  url:            'mesfind.github.io'
  email:          'mesfindiro@gmail.com'
  github:         'https://github.com/mesfind'
  facebook:       'http://www.facebook.com/ILikeDataEdge'
  twitter:        'https://twitter.com/mesfindiro'
  googleplus:     ''
  linkedin:       'https://www.linkedin.com/in/mesfindiro '
  disqus_shortname: mesfind

paginate:         3
 paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/MesfinD/mesfind.github.io

# Collections
collections:
  - projects
  - talks

# defaults:
#   -
#     scope:
#       path: ""
#       type: "projects" # a collection in your site, in plural form
#     values:
#       layout: "default"
# Default Settings

defaults:
  -
    scope:
      path: "" 			# an empty string here means all files in the project
      type: "pages"
    values:
      show_meta: false		# Hide metadata for all pages
      # sidebar:    		# Possible values › left, right › by default there will be no sidebar
      comments: true
      author: mesfind		# Default author for pages
  -
    scope:
      path: ""
      type: "posts"
    values:
      show_meta: true		# Show metadata for all posts
      # sidebar:		# Possible values › left, right › by default there will be no sidebar
      comments: true
      author: mesfind		# Default author for posts
